# Docker Compose for Bio-MCP Development Environment

services:
  bio-mcp:
    build: .
    container_name: bio-mcp-server
    environment:
      - BIO_MCP_LOG_LEVEL=DEBUG
      - BIO_MCP_SERVER_NAME=bio-mcp-dev
      # Phase 1A: Basic setup with environment defaults
      - DATABASE_URL=sqlite:///data/bio-mcp.db
      - WEAVIATE_URL=http://weaviate:8080  # Internal container-to-container communication still uses 8080
      # API keys can be set via .env file
      - PUBMED_API_KEY=${PUBMED_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./data:/app/data
    depends_on:
      - weaviate
    stdin_open: true
    tty: true
    # MCP uses stdio, so we'll run interactively for testing

  # Weaviate vector database - version matches serverless cloud compatibility
  weaviate:
    image: semitechnologies/weaviate:1.30.0
    container_name: bio-mcp-weaviate
    ports:
      - "8080:8080"   # HTTP/REST API - standard port for local dev
      - "50051:50051" # gRPC API - standard port for local dev
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
    depends_on:
      - t2v-transformers

  # Transformer model for embeddings (we'll use a working model first)
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    container_name: bio-mcp-transformers
    environment:
      ENABLE_CUDA: '0'  # Set to '1' if you have GPU support
    volumes:
      - weaviate_data:/var/lib/weaviate

  # PostgreSQL for future phases
  postgres:
    image: postgres:15-alpine
    container_name: bio-mcp-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Use 5433 to avoid conflicts with existing PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: bio-mcp-minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  weaviate_data:
  postgres_data:
  minio_data: